# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
        exclude: ^template/pyproject.toml$
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [ --autofix ]
      - id: detect-private-key

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [ tomli ]
        args: [ --in-place, --config, ./pyproject.toml ]
        exclude: ^(notebooks)/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes ]
      - id: ruff-format

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
      - id: mypy
