name: "pdm-conda"

services:
  pdm-conda:
    build:
      context: ../
      dockerfile: ./base/Dockerfile
      args:
        project_type: "lib"
    platform: linux/amd64
    image: pdm-conda:latest
    restart: always
