name: "pdm-conda-dev"

services:
  pdm-conda:
    user: root
    build:
      args:
        env: "dev"
        dependencies: ":all"
        local_path: $PWD
    image: pdm-conda:latest-dev
    platform: linux/arm64
    volumes:
      - ../tests:/app/tests
      - ../src/pdm_conda:/app/src/pdm_conda
      - ../scripts:/app/scripts
      - ../.dev.env:/app/.env
      - ../pdm.lock:/app/pdm.lock
      - ../pyproject.toml:/app/pyproject.toml
      - ../coverage.xml:/app/coverage.xml
