name: "pdm-conda-dev"

services:
  pdm-conda:
    user: root
    build:
      args:
        env: "dev"
        dependencies: ":all"
    image: pdm-conda:latest-dev
    platform: linux/arm64
    volumes:
      - ../:/app/
      - ../.env:/app/.env
      - /app/.pdm-plugins
      - /app/dist
