services:
  pdm-conda:
    build:
      args:
        env: dev
    image: pdm-conda:latest-dev
    platform: linux/arm64
    user: root
    volumes:
      - ../:/app/
      - /app/.pdm-plugins
      - /app/dist
