name: "pdm-conda"

services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        project_type: "lib"
    platform: linux/amd64
    image: pdm-conda:latest
    restart: always
    env_file:
      - ../.env
