name: "pdm-conda"

services:
  pdm-conda:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
      args:
        src: ./src
    image: pdm-conda:latest
    restart: always
    platform: linux/amd64
